### ISSUE TITLE
打开应用后，显示在里面的就是支持FCM的吗

### ISSUE THREAD

**Issue by xinzhang-hello** [HappyMax0/FCMPushViewer#2]
如题

**Comment by HappyMax0** [comment]
是的，理论上支持，只是某些大陆app注册不注册上fcm推送不一定，一些好像看你是+86账号就不注册。



奈业 Galaxy 魉



-------- 原始息 --------
自： xinzhang-hello ***@***.***>
日期： 2023/12/5 09:17 (GMT+08:00)
至： HappyMax0/FCMPushViewer ***@***.***>
副本： Subscribed ***@***.***>
主旨： [HappyMax0/FCMPushViewer] 打开应用后，显示在里面的就是支持FCM的吗 (Issue #2)


如题

―

**Comment by xinzhang-hello** [comment]
好的 感谢。 Gmail感觉也感觉有延迟，从iPhone换过来的用户，还没有搞清楚为啥

**Comment by zyh941** [comment]
> 好的 感谢。 Gmail感觉也感觉有延迟，从iPhone换过来的用户，还没有搞清楚为啥

很简单，因为Android版GMAIL走的是系统同步来收新邮件，而不是用自家的fcm推送，谷歌曾说过邮件非即时工具，不需及时收到，所以完全不改，当然是要装第三方邮件来用fcm推送啦

**Comment by HappyMax0** [comment]
可以用outlook收，虽然我接收gmail是没问题

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________

**Comment by zyh941** [comment]
outlook就是用fcm推送

**Comment by xinzhang-hello** [comment]
感谢各位回复。我目前测下来，用V2RayNG，开启应用级别的FQ后（原来为默认配置）好像FCM推送都好了，其他的细节我就没有再继续追究了。
